/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import ClaseseInterfaces.Electrodomestico;
import ClaseseInterfaces.RetoLaboratorio10;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author Frank
 */
public class RegistroElectrodomestico extends javax.swing.JFrame {

    List<Electrodomestico> listaelectro = new ArrayList<>();
    
    private DefaultListModel<String> modelListaElec;
    
    /**
     * Creates new form RegistroElectrodomestico
     */
    public RegistroElectrodomestico() {
        initComponents(); 
        modelListaElec = new DefaultListModel<>();
        this.lstElectrodomesticos.setModel(modelListaElec);
        
        modelListaElec.removeAllElements();
        
        for (Electrodomestico electrodomestico : RetoLaboratorio10.listaelectro) {
            modelListaElec.addElement(electrodomestico.mostrarElec());
        }
    }
    
    public void actualizarListaElectro() {
        modelListaElec.clear(); // Limpia el modelo
        for (Electrodomestico electrodomestico : RetoLaboratorio10.listaelectro) {
            modelListaElec.addElement(electrodomestico.mostrarElec());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstElectrodomesticos = new javax.swing.JList<>();
        btnCerrar = new javax.swing.JButton();
        btnPlancha = new javax.swing.JButton();
        btnLicuadora = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnWaflera = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lstElectrodomesticos.setBackground(new java.awt.Color(153, 204, 255));
        lstElectrodomesticos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lstElectrodomesticos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lstElectrodomesticos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstElectrodomesticos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 390, 320));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesFigma/btnCerrar.png"))); // NOI18N
        btnCerrar.setBorder(null);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 50, 50));

        btnPlancha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPlancha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesFigma/btnPlancha.png"))); // NOI18N
        btnPlancha.setBorder(null);
        btnPlancha.setContentAreaFilled(false);
        btnPlancha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlanchaActionPerformed(evt);
            }
        });
        jPanel1.add(btnPlancha, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 160, 60));

        btnLicuadora.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLicuadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesFigma/btnLicuadora.png"))); // NOI18N
        btnLicuadora.setBorder(null);
        btnLicuadora.setContentAreaFilled(false);
        btnLicuadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLicuadoraActionPerformed(evt);
            }
        });
        jPanel1.add(btnLicuadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 210, -1, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesFigma/lblElec.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnWaflera.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnWaflera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesFigma/btnWaflera.png"))); // NOI18N
        btnWaflera.setBorder(null);
        btnWaflera.setContentAreaFilled(false);
        btnWaflera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWafleraActionPerformed(evt);
            }
        });
        jPanel1.add(btnWaflera, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 150, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnPlanchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlanchaActionPerformed

        AgregarPlancha plancha = new AgregarPlancha(this);
        plancha.setLocationRelativeTo(this);
        plancha.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnPlanchaActionPerformed

    private void btnLicuadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLicuadoraActionPerformed

        AgregarLicuadora licuadora = new AgregarLicuadora(this);
        licuadora.setLocationRelativeTo(this);
        licuadora.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLicuadoraActionPerformed

    private void btnWafleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWafleraActionPerformed

        AgregarWaflera waflera = new AgregarWaflera(this);
        waflera.setLocationRelativeTo(this);
        waflera.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnWafleraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroElectrodomestico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroElectrodomestico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroElectrodomestico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroElectrodomestico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroElectrodomestico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnLicuadora;
    private javax.swing.JButton btnPlancha;
    private javax.swing.JButton btnWaflera;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstElectrodomesticos;
    // End of variables declaration//GEN-END:variables
}
